apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-hw09
spec:
  selector:
    matchLabels:
      app: web-server-hw09
  template:
    metadata:
      labels:
        app: web-server-hw09
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: service-account-key
      containers:
      - name: web-server-hw09
        image: us-west2-docker.pkg.dev/ds561-trial-project/docker-hw09/web-server-hw09:1.0.0
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/cluster-hw09.json